set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
 	set_property IOSTANDARD LVCMOS33 [get_ports clk] 
 create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk] 


set_property PACKAGE_PIN U16 [get_ports {anodes[0]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}] 
set_property PACKAGE_PIN E19 [get_ports {anodes[1]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}] 
set_property PACKAGE_PIN U19 [get_ports {anodes[2]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}] 
set_property PACKAGE_PIN V19 [get_ports {anodes[3]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}] 
set_property PACKAGE_PIN W18 [get_ports {anodes[4]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[4]}] 
set_property PACKAGE_PIN U15 [get_ports {anodes[5]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[5]}] 
set_property PACKAGE_PIN U14 [get_ports {anodes[6]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[6]}] 
set_property PACKAGE_PIN V14 [get_ports {anodes[7]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[7]}] 
set_property PACKAGE_PIN V13 [get_ports {katodes[0]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[0]}] 
set_property PACKAGE_PIN V3 [get_ports {katodes[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[1]}] 
set_property PACKAGE_PIN W3 [get_ports {katodes[2]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[2]}] 
set_property PACKAGE_PIN U3 [get_ports {katodes[3]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[3]}] 
set_property PACKAGE_PIN P3 [get_ports {katodes[4]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[4]}] 
set_property PACKAGE_PIN N3 [get_ports {katodes[5]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[5]}] 
set_property PACKAGE_PIN P1 [get_ports {katodes[6]}]  	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {katodes[6]}] 
set_property PACKAGE_PIN L1 [get_ports {katodes[7]}]  	 	 	 	  			
set_property IOSTANDARD LVCMOS33 [get_ports {katodes[7]}] 



set_property PACKAGE_PIN U18 [get_ports StartButton]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports StartButton] 
set_property PACKAGE_PIN T18 [get_ports ResetButton]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports ResetButton] 
set_property PACKAGE_PIN W19 [get_ports LButton]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports LButton] 
set_property PACKAGE_PIN T17 [get_ports RButton]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports RButton] 
set_property PACKAGE_PIN U17 [get_ports Pause]  	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports Pause] 

